/*
 * Copyright 2025 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.gformstubs.controllers

import play.api.mvc.{ AbstractController, Action, AnyContent, ControllerComponents }
import uk.gov.hmrc.gformstubs.model.IndiaFTARegistration

import java.time.temporal.ChronoUnit
import java.time.{ Instant, ZoneOffset, ZonedDateTime }
import javax.inject.{ Inject, Singleton }
import scala.concurrent.Future

@Singleton
class ContainerManagedArchitecture @Inject() (controllerComponents: ControllerComponents)
    extends AbstractController(controllerComponents) {

  def postVatParcelsC2C() = Action.async { _ =>
    val instant: String =
      ZonedDateTime.ofInstant(Instant.now(), ZoneOffset.UTC).truncatedTo(ChronoUnit.SECONDS).toString

    Future.successful(
      Ok(
        s"""
           |{
           |  "success": {
           |    "processingDate": "$instant"
           |  }
           |}
           |""".stripMargin
      ).as("application/json")
    )
  }

  def indiaFTARegister() = Action(parse.json[IndiaFTARegistration]) { request =>
    val businessName = request.body.BusinessName.toLowerCase()
    val correlationId = request.headers.get("X-Correlation-Id")
    val instant: String =
      ZonedDateTime.ofInstant(Instant.now(), ZoneOffset.UTC).truncatedTo(ChronoUnit.SECONDS).toString

    if (businessName.contains("error"))
      InternalServerError(
        s"""|{
            |  "errorDetail": {
            |    "errorCode": "500",
            |    "errorMessage": "Unknown error occurred",
            |    "source": "journey-<journey-name>-service-camel",
            |    "sourceFaultDetail": {},
            |    "timestamp": "$instant",
            |    "correlationId": "${correlationId.getOrElse("unknown")}"
            |  }
            |}""".stripMargin
      ).as("application/json")
    else
      Ok(
        s"""|{
            |  "pyStatusValue": "Success"
            |}
            |""".stripMargin
      ).as("application/json")
  }

  def respJson(respCode: Int = 200, body: String) = Status(respCode).apply(body).as("application/json")

  def indiaFTAGetManageEmails(eori: String): Action[AnyContent] = Action { implicit request =>
    val timestamp: String = Instant.now().toString
    val correlationId = request.headers.get("X-Correlation-Id").fold("e9339322-7840-4099-a543-ae771bf02271")(identity)

    if (eori.contains("500400")) {
      respJson(
        500,
        s"""
           |{
           |  "errorDetail": {
           |    "errorCode": "500",
           |    "errorMessage": "HTTP operation failed invoking http://pds:80/pds/cnit/manageEmails/V1/$eori/INFT with statusCode: 400",
           |    "source": "Backend",
           |    "sourceFaultDetail": {
           |      "detail": [
           |        "HTTP operation failed invoking http://pds:80/pds/cnit/manageEmails/V1/$eori/INFT with statusCode: 400"
           |      ]
           |    },
           |    "timestamp": "$timestamp",
           |    "correlationId": "$correlationId"
           |  }
           |}
           |""".stripMargin
      )
    } else if (eori.contains("500404")) {
      respJson(
        500,
        s"""
           |{
           |  "errorDetail": {
           |    "errorCode": "500",
           |    "errorMessage": "HTTP operation failed invoking http://pds:80/pds/cnit/manageEmails/V1/$eori/INFT with statusCode: 404",
           |    "source": "Backend",
           |    "sourceFaultDetail": {
           |      "detail": [
           |        "HTTP operation failed invoking http://pds:80/pds/cnit/manageEmails/V1/$eori/INFT with statusCode: 404"
           |      ]
           |    },
           |    "timestamp": "$timestamp",
           |    "correlationId": "$correlationId"
           |  }
           |}
           |""".stripMargin
      )
    } else if (eori.contains("503")) {
      respJson(
        503,
        s"""{
           |  "errorDetail": {
           |    "errorCode": "503",
           |    "errorMessage": "<detail as generated by service>",
           |    "source": "journey-<journey-name>-service-camel",
           |    "sourceFaultDetail": {
           |      "detail": [
           |        "<detail as generated by service>"
           |      ]
           |    },
           |    "timestamp": "$timestamp",
           |    "correlationId": "$correlationId"
           |  }
           |}""".stripMargin
      )
    } else if (eori.contains("111111")) {
      respJson(
        200,
        """{
          |"primaryEmail": "primary@domain.com",
          |"secondaryEmails": []
          |}""".stripMargin
      )
    } else if (eori.contains("222222")) {
      respJson(
        200,
        """{
          |"primaryEmail": "primary@domain.com",
          |"secondaryEmails": ["test1@somewhere.com", "test2@elsewhere.co.uk"]
          |}""".stripMargin
      )
    } else if (eori.contains("101010")) {
      respJson(
        200,
        """{
          |"primaryEmail": "primary@domain.com",
          |"secondaryEmails": [
          |"secondary-1@domain.com",
          |"secondary-2@domain.com",
          |"secondary-3@domain.com",
          |"secondary-4@domain.com",
          |"secondary-5@domain.com",
          |"secondary-6@domain.com",
          |"secondary-7@domain.com",
          |"secondary-8@domain.com",
          |"secondary-9@domain.com",
          |"secondary-10@domain.com"
          |]
          |}""".stripMargin
      )
    } else {
      respJson(
        200,
        """{
          |"primaryEmail": "primary@domain.com",
          |"secondaryEmails": [
          |"secondary-1@domain.com",
          |"secondary-2@domain.com ",
          |"secondary-3@domain.com "
          |]
          |}""".stripMargin
      )
    }

  }

  def indiaFTAPostManageEmails(eori: String) = Action { implicit request =>
    if (eori.contains("400")) {
      respJson(
        400,
        body = """{
                 |  "errorDetail": {
                 |    "errorCode": "400",
                 |    "errorMessage": "Invalid query parameter",
                 |    "source": "journey-fta02-service-camel",
                 |    "sourceFaultDetail": {
                 |      "detail": [
                 |        "Invalid query parameter"
                 |      ]
                 |    },
                 |    "timestamp": "2020-09-25T21:54:12.015Z",
                 |    "correlationId": "1ae81b45-41b4-4642-ae1c-db1126900001"
                 |  }
                 |}""".stripMargin
      )
    } else if (eori.contains("500")) {
      respJson(
        500,
        """{
          |  "errorDetail": {
          |    "errorCode": "500",
          |    "errorMessage": "<detail as generated by service>",
          |    "source": "journey-<journey-name>-service-camel",
          |    "sourceFaultDetail": {
          |      "detail": [
          |        "<detail as generated by service>"
          |      ]
          |    },
          |    "timestamp": "2020-09-28T14:31:41.286Z",
          |    "correlationId": "d60de98c-f499-47f5-b2d6-e80966e8d19e"
          |  }
          |}""".stripMargin
      )
    } else if (eori.contains("503")) {
      respJson(
        503,
        """{
          |  "errorDetail": {
          |    "errorCode": "503",
          |    "errorMessage": "<detail as generated by service>",
          |    "source": "journey-<journey-name>-service-camel",
          |    "sourceFaultDetail": {
          |      "detail": [
          |        "<detail as generated by service>"
          |      ]
          |    },
          |    "timestamp": "2020-09-30T14:01:32.786Z",
          |    "correlationId": "e9339322-7840-4099-a543-ae771bf02271"
          |  }
          |}""".stripMargin
      )
    } else {
      Ok("")
    }
  }
}
